services:
  kokowaf:
    restart: always
    build: .
    ports:
      - "5008:8081"
    environment:
      DYN_FLAG: BHFlagY{FakeFlag}
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://127.0.0.1:80 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3