[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "gevent>=25.9.1",
    "gunicorn>=23.0.0",
    "requests>=2.32.5",
]
